<a href="https://colab.research.google.com/github/KaderKarasakal/python-exercises/blob/main/matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow
!pip install numpy

In [ ]:
import tensorflow as tf
import numpy as np


In [ ]:
changeable_tensor= tf.Variable([2,3])
unchangeable_tensor=tf.constant([2,3])
unchangeable_tensor , changeable_tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(7) # birinci terime 7 atadı
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 3], dtype=int32)>

random tensors

In [ ]:
random_1= tf.random.Generator.from_seed(42) # set seed for reproductability
random_1=random_1.normal(shape=(2,3))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))
random_1, random_2, random_1==random_2



(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=bool, numpy=False>)

shuffle order of each elements in tensorflow

In [ ]:
not_shuffled=tf.constant([[10,7],
                         [3,4],
                         [2,1]])
not_shuffled.ndim,
tf.random.shuffle(not_shuffled)# shuffle our not_shuffled tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  1],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)  #global level random seed
tf.random.shuffle(not_shuffled, seed=42)  # operation level random seed
# global ve operation level olunca random olmadı


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  1]], dtype=int32)>

# you can also turn NumPy arrays to tensors
**The main diffence between numpy arrays and tensors is that tensors can be run on a GPU (much faster)**
# A=tf.constant(some_matrix) #capital for matrix or tensor
# b=tf.constant(vectors) # non-capital for vector


In [ ]:
numpy_A= np.arange(1,25, dtype=np.int32) # create a array from 1 to 25
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A=tf.constant(numpy_A, shape=(3,2,4))
B = tf.constant(numpy_A)
A,B, A.ndim

(<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]],
 
        [[17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 3)

# Getting information from tensors


In [ ]:
rank_4= tf.ones([2,3,4,5])
rank_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [ ]:
rank_4.ndim, rank_4.shape, tf.size(rank_4)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#get various attributes of our tensor
print("datatype of every elements(dtype): ", rank_4.dtype)
print("number of dimension(rank): ", rank_4.ndim)
print("shape of the tenssor: ", rank_4.shape)
print("element along the last axis: ", rank_4.shape[-1])
print("element along the first axis: ",  rank_4.shape[0])
print("total number of elements of our tensor(size): ", tf.size(rank_4))


datatype of every elements(dtype):  <dtype: 'float32'>
number of dimension(rank):  4
shape of the tenssor:  (2, 3, 4, 5)
element along the last axis:  5
element along the first axis:  2
total number of elements of our tensor(size):  tf.Tensor(120, shape=(), dtype=int32)


# Index

In [ ]:
#get first 2 elements from each dimension
some_list=[1,2,3,4,5]
some_list[:2]

[1, 2]

In [ ]:
#rank_4[:2,:2,:2,:2]
rank_4[:1,:2,:,:]

<tf.Tensor: shape=(1, 2, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

# tf.newaxis

In [ ]:
#add extra dimension
rank_5=rank_4[...,tf.newaxis]
rank_5

In [ ]:
tensor_2=tf.constant([[2,3],
                      [4,5]])
tensor_2


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
#alternative to tf.newaxis
tf.expand_dims(tensor_2, axis=-1)#expand the last dimension


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>

# manipulating tensors(tensor operation)
+-/*

multiplication matrix

In [ ]:
print(tensor_2)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [ ]:
tf.matmul(tensor_2, tensor_2) #matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 21],
       [28, 37]], dtype=int32)>

In [ ]:
tensor_2 @ tensor_2 # @ is matrix multiplication symbol in python

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[16, 21],
       [28, 37]], dtype=int32)>

In [ ]:
#create a new tensor with default datatype(float32)
B=tf.constant([1.7, 7.4])
B.dtype, B

(tf.float32,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>)

In [ ]:
C= tf.constant([7, 10])
C.dtype

tf.int32

In [ ]:
# change from float32 to float 16 (reduced precision) daha az hassas ve iki kat daha hızlı
B=tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
#change from int32 to int16
C=tf.cast(C, dtype=tf.int16)
C, C.dtype

(<tf.Tensor: shape=(2,), dtype=int16, numpy=array([ 7, 10], dtype=int16)>,
 tf.int16)

## aggregate
aggregating tensors: condensing them from multıple values to a smaller amount of values

In [ ]:
D=tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D) # absolute value

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

#  let's go through the following forms of aggregation
*   get the minimum
*   get the maximum
*   get the mean of the tensors
*    get the sum of the tensor







In [ ]:
#create a random tensor with betwwen 0 and 100, size 50
E=tf.constant(np.random.randint(0,100, size=50))
E, tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([17, 12, 45, 67, 71, 40, 55, 57, 28, 69, 82, 29, 75, 98, 30, 40, 31,
         9, 87, 14, 67, 53, 15, 14, 35, 71, 99, 86, 34, 14,  7, 17, 29, 21,
        33, 27, 51, 89,  0, 84, 50, 77, 92, 62,  0, 32, 70, 18, 58, 28])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=50>,
 TensorShape([50]),
 1)

In [ ]:
# find the minimum
tf.reduce_min(E)



<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2289>

In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=788>

In [ ]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32)) # dtype must be real or complex, that's why we converted from int to float

<tf.Tensor: shape=(), dtype=float32, numpy=28.071545>

In [ ]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=788.01166>

# positional maximum and minimum


In [ ]:
#create a new random tensor for finding positional minimum and maximum
tf.random.set_seed(42) # böylece her seferinde aynı kalıyor
F=tf.random.uniform([50])
F

In [ ]:
#find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
F[tf.argmax(F)]== tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
F[tf.argmin(F)]== tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# Squeezing a tensor (removing all single dimensions)

In [ ]:
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

In [ ]:
G_squeezed=tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

# One-hot encoding tensors

In [ ]:
#create a list of indices
some_list=[0,1,2,3] #blue, yellow, red, puple

#one hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="I love deep learning", off_value="I also like dancing")


<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love deep learning', b'I also like dancing',
        b'I also like dancing', b'I also like dancing'],
       [b'I also like dancing', b'I love deep learning',
        b'I also like dancing', b'I also like dancing'],
       [b'I also like dancing', b'I also like dancing',
        b'I love deep learning', b'I also like dancing'],
       [b'I also like dancing', b'I also like dancing',
        b'I also like dancing', b'I love deep learning']], dtype=object)>

# Squaring, Log, Squareroot

In [ ]:
#create a new tensor
H=tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(H)# won't work with int32,  it's dtype must be bfloat16, half, float, double, complex64, complex128

In [ ]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H, dtype=tf.float32))

# Tensors and NumPy array

In [ ]:
#create a new tensor directly from a numpy array
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#convert our tensor back to numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#convert tensor J to numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#the default types are slightly different
tensor_J= tf.constant([3.,7.,10.])
numpy_J=tf.constant(np.array([3.,7.,10]))
tensor_J.dtype, numpy_J.dtype

(tf.float32, tf.float64)

INTERMISSION

In [ ]:
import sys

sys.getsizeof(int(5))




28